#!/usr/bin/env bash
# Comprueba qué URLs RSS del seed responden con HTTP 200.
# Uso: bash check_rss_urls.sh

URLS=(
  # El País (10)
  "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada"
  "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/economia/portada"
  "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ciencia/portada"
  "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/cultura/portada"
  "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/deportes/portada"
  "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/sociedad/portada"
  "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/espana/portada"
  "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/clima-y-medio-ambiente/portada"
  "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/internacional/portada"
  "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/educacion/portada"
  # El Mundo (10)
  "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml"
  "https://e00-elmundo.uecdn.es/elmundo/rss/economia.xml"
  "https://e00-elmundo.uecdn.es/elmundo/rss/cultura.xml"
  "https://e00-elmundo.uecdn.es/elmundo/rss/internacional.xml"
  "https://www.elmundo.es/rss/tecnologia.xml"
  "https://www.elmundo.es/rss/deportes.xml"
  "https://www.elmundo.es/rss/salud.xml"
  "https://www.elmundo.es/rss/sociedad.xml"
  "https://www.elmundo.es/rss/motor.xml"
  "https://www.elmundo.es/rss/cronica.xml"
  # ABC (8)
  "https://www.abc.es/rss/feeds/abc_Espana.xml"
  "https://www.abc.es/rss/feeds/abc_Economia.xml"
  "https://www.abc.es/rss/feeds/abc_Ciencia.xml"
  "https://www.abc.es/rss/feeds/abc_Cultura.xml"
  "https://www.abc.es/rss/feeds/abc_Deportes.xml"
  "https://www.abc.es/rss/feeds/abc_Internacional.xml"
  "https://www.abc.es/rss/feeds/abc_Familia.xml"
  "https://www.abc.es/rss/feeds/abc_Religion.xml"
  # La Vanguardia (10)
  "https://www.lavanguardia.com/rss/home.xml"
  "https://www.lavanguardia.com/rss/economia.xml"
  "https://www.lavanguardia.com/rss/ciencia.xml"
  "https://www.lavanguardia.com/rss/cultura.xml"
  "https://www.lavanguardia.com/rss/deportes.xml"
  "https://www.lavanguardia.com/rss/salud.xml"
  "https://www.lavanguardia.com/rss/vida.xml"
  "https://www.lavanguardia.com/rss/medioambiente.xml"
  "https://www.lavanguardia.com/rss/internacional.xml"
  "https://www.lavanguardia.com/rss/motor.xml"
  # Euronews España (5)
  "https://es.euronews.com/rss"
  "https://es.euronews.com/rss?level=theme&name=news"
  "https://es.euronews.com/rss?level=theme&name=business"
  "https://es.euronews.com/rss?level=theme&name=sport"
  "https://es.euronews.com/rss?level=theme&name=weather"
  # Expansión (10)
  "https://e00-expansion.uecdn.es/rss/portada.xml"
  "https://e00-expansion.uecdn.es/rss/mercados.xml"
  "https://e00-expansion.uecdn.es/rss/empresas.xml"
  "https://e00-expansion.uecdn.es/rss/economia-politica.xml"
  "https://e00-expansion.uecdn.es/rss/ahorro.xml"
  "https://e00-expansion.uecdn.es/rss/tecnologia.xml"
  "https://e00-expansion.uecdn.es/rss/empleo.xml"
  "https://e00-expansion.uecdn.es/rss/opinion.xml"
  "https://e00-expansion.uecdn.es/rss/juridico.xml"
  "https://e00-expansion.uecdn.es/rss/catalunya.xml"
  # Marca (10)
  "https://e00-marca.uecdn.es/rss/portada.xml"
  "https://e00-marca.uecdn.es/rss/futbol.xml"
  "https://e00-marca.uecdn.es/rss/baloncesto.xml"
  "https://e00-marca.uecdn.es/rss/tenis.xml"
  "https://e00-marca.uecdn.es/rss/motor.xml"
  "https://e00-marca.uecdn.es/rss/ciclismo.xml"
  "https://e00-marca.uecdn.es/rss/golf.xml"
  "https://e00-marca.uecdn.es/rss/atletismo.xml"
  "https://e00-marca.uecdn.es/rss/boxeo.xml"
  "https://e00-marca.uecdn.es/rss/padel.xml"
  # El Confidencial (10)
  "https://rss.elconfidencial.com/espana/"
  "https://rss.elconfidencial.com/mercados/"
  "https://rss.elconfidencial.com/tecnologia/"
  "https://rss.elconfidencial.com/cultura/"
  "https://rss.elconfidencial.com/deportes/"
  "https://rss.elconfidencial.com/sociedad/"
  "https://rss.elconfidencial.com/mundo/"
  "https://rss.elconfidencial.com/empresas/"
  "https://rss.elconfidencial.com/tendencias/"
  "https://rss.elconfidencial.com/ultima-hora-nacional/"
  # 20 Minutos (10)
  "https://www.20minutos.es/rss/"
  "https://www.20minutos.es/rss/economia/"
  "https://www.20minutos.es/rss/tecnologia/"
  "https://www.20minutos.es/rss/deportes/"
  "https://www.20minutos.es/rss/salud/"
  "https://www.20minutos.es/rss/nacional/"
  "https://www.20minutos.es/rss/internacional/"
  "https://www.20minutos.es/rss/ciencia/"
  "https://www.20minutos.es/rss/motor/"
  "https://www.20minutos.es/rss/medio-ambiente/"
  # elDiario.es (1)
  "https://www.eldiario.es/rss/"
  # Mundo Deportivo (15) — confirmadas en FeedSpot
  "https://www.mundodeportivo.com/feed/rss/home"
  "https://www.mundodeportivo.com/feed/rss/futbol"
  "https://www.mundodeportivo.com/feed/rss/futbol/internacional"
  "https://www.mundodeportivo.com/feed/rss/baloncesto"
  "https://www.mundodeportivo.com/feed/rss/motor"
  "https://www.mundodeportivo.com/feed/rss/motor/f1"
  "https://www.mundodeportivo.com/feed/rss/tenis"
  "https://www.mundodeportivo.com/feed/rss/futbol/champions-league"
  "https://www.mundodeportivo.com/feed/rss/futbol/premier-league"
  "https://www.mundodeportivo.com/feed/rss/futbol/serie-a"
  "https://www.mundodeportivo.com/feed/rss/futbol/bundesliga"
  "https://www.mundodeportivo.com/feed/rss/futbol/europa-league"
  "https://www.mundodeportivo.com/feed/rss/rugby"
  "https://www.mundodeportivo.com/feed/rss/boxeo"
  "https://www.mundodeportivo.com/feed/rss/atletismo"
  # BBC Mundo (10)
  "https://feeds.bbci.co.uk/mundo/rss.xml"
  "https://feeds.bbci.co.uk/mundo/noticias/america_latina/rss.xml"
  "https://feeds.bbci.co.uk/mundo/noticias/internacional/rss.xml"
  "https://feeds.bbci.co.uk/mundo/noticias/economia/rss.xml"
  "https://feeds.bbci.co.uk/mundo/noticias/ciencia_tecnologia/rss.xml"
  "https://feeds.bbci.co.uk/mundo/noticias/salud/rss.xml"
  "https://feeds.bbci.co.uk/mundo/noticias/cultura/rss.xml"
  "https://feeds.bbci.co.uk/mundo/noticias/deportes/rss.xml"
  "https://feeds.bbci.co.uk/mundo/noticias/medio_ambiente/rss.xml"
  "https://feeds.bbci.co.uk/mundo/noticias/sociedad/rss.xml"
  # El Español (1)
  "https://www.elespanol.com/rss/"
  # La Vanguardia extra (26) — confirmadas FeedSpot
  "https://www.lavanguardia.com/rss/politica.xml"
  "https://www.lavanguardia.com/rss/opinion.xml"
  "https://www.lavanguardia.com/rss/gente.xml"
  "https://www.lavanguardia.com/rss/sucesos.xml"
  "https://www.lavanguardia.com/rss/participacion.xml"
  "https://www.lavanguardia.com/rss/lacontra.xml"
  "https://www.lavanguardia.com/rss/natural.xml"
  "https://www.lavanguardia.com/rss/vida/salud.xml"
  "https://www.lavanguardia.com/rss/tecnologia.xml"
  "https://www.lavanguardia.com/rss/local/catalunya.xml"
  "https://www.lavanguardia.com/rss/local/paisvasco.xml"
  "https://www.lavanguardia.com/rss/local/valencia.xml"
  "https://www.lavanguardia.com/rss/local/sevilla.xml"
  "https://www.lavanguardia.com/rss/local/madrid.xml"
  "https://www.lavanguardia.com/rss/local/girona.xml"
  "https://www.lavanguardia.com/rss/local/lleida.xml"
  "https://www.lavanguardia.com/rss/local/tarragona.xml"
  "https://www.lavanguardia.com/rss/local/barcelona.xml"
  "https://www.lavanguardia.com/rss/comer.xml"
  "https://www.lavanguardia.com/rss/mascotas.xml"
  "https://www.lavanguardia.com/rss/vivo.xml"
  "https://www.lavanguardia.com/rss/magazine.xml"
  "https://www.lavanguardia.com/rss/series.xml"
  "https://www.lavanguardia.com/rss/television.xml"
  "https://www.lavanguardia.com/rss/mamas-y-papas.xml"
  "https://www.lavanguardia.com/rss/ocio/viajes.xml"
  # Marca extra (53) — confirmadas FeedSpot
  "https://e00-marca.uecdn.es/rss/futbol/primera-division.xml"
  "https://e00-marca.uecdn.es/rss/futbol/segunda-division.xml"
  "https://e00-marca.uecdn.es/rss/futbol/mas-futbol.xml"
  "https://e00-marca.uecdn.es/rss/futbol/copa-rey.xml"
  "https://e00-marca.uecdn.es/rss/futbol/seleccion.xml"
  "https://e00-marca.uecdn.es/rss/futbol/futbol-sala.xml"
  "https://e00-marca.uecdn.es/rss/futbol/futbol-internacional.xml"
  "https://e00-marca.uecdn.es/rss/futbol/champions-league.xml"
  "https://e00-marca.uecdn.es/rss/futbol/europa-league.xml"
  "https://e00-marca.uecdn.es/rss/futbol/premier-league.xml"
  "https://e00-marca.uecdn.es/rss/futbol/bundesliga.xml"
  "https://e00-marca.uecdn.es/rss/futbol/liga-francesa.xml"
  "https://e00-marca.uecdn.es/rss/futbol/mundial-de-clubes.xml"
  "https://e00-marca.uecdn.es/rss/futbol/america.xml"
  "https://e00-marca.uecdn.es/rss/futbol/real-madrid.xml"
  "https://e00-marca.uecdn.es/rss/futbol/barcelona.xml"
  "https://e00-marca.uecdn.es/rss/futbol/atletico.xml"
  "https://e00-marca.uecdn.es/rss/futbol/sevilla.xml"
  "https://e00-marca.uecdn.es/rss/futbol/athletic.xml"
  "https://e00-marca.uecdn.es/rss/futbol/villarreal.xml"
  "https://e00-marca.uecdn.es/rss/futbol/real-sociedad.xml"
  "https://e00-marca.uecdn.es/rss/futbol/betis.xml"
  "https://e00-marca.uecdn.es/rss/futbol/celta.xml"
  "https://e00-marca.uecdn.es/rss/futbol/osasuna.xml"
  "https://e00-marca.uecdn.es/rss/futbol/mallorca.xml"
  "https://e00-marca.uecdn.es/rss/futbol/alaves.xml"
  "https://e00-marca.uecdn.es/rss/futbol/getafe.xml"
  "https://e00-marca.uecdn.es/rss/futbol/rayo.xml"
  "https://e00-marca.uecdn.es/rss/futbol/levante.xml"
  "https://e00-marca.uecdn.es/rss/futbol/leganes.xml"
  "https://e00-marca.uecdn.es/rss/futbol/girona.xml"
  "https://e00-marca.uecdn.es/rss/futbol/las-palmas.xml"
  "https://e00-marca.uecdn.es/rss/futbol/tenerife.xml"
  "https://e00-marca.uecdn.es/rss/futbol/elche.xml"
  "https://e00-marca.uecdn.es/rss/futbol/malaga.xml"
  "https://e00-marca.uecdn.es/rss/futbol/deportivo.xml"
  "https://e00-marca.uecdn.es/rss/futbol/zaragoza.xml"
  "https://e00-marca.uecdn.es/rss/futbol/sporting.xml"
  "https://e00-marca.uecdn.es/rss/futbol/oviedo.xml"
  "https://e00-marca.uecdn.es/rss/futbol/racing-santander.xml"
  "https://e00-marca.uecdn.es/rss/futbol/lugo.xml"
  "https://e00-marca.uecdn.es/rss/futbol/mirandes.xml"
  "https://e00-marca.uecdn.es/rss/futbol/fuenlabrada.xml"
  "https://e00-marca.uecdn.es/rss/futbol/alcorcon.xml"
  "https://e00-marca.uecdn.es/rss/futbol/numancia.xml"
  "https://e00-marca.uecdn.es/rss/futbol/ponferradina.xml"
  "https://e00-marca.uecdn.es/rss/futbol/eibar.xml"
  "https://e00-marca.uecdn.es/rss/futbol/granada.xml"
  "https://e00-marca.uecdn.es/rss/baloncesto/nba.xml"
  "https://e00-marca.uecdn.es/rss/baloncesto/copa-rey.xml"
  "https://e00-marca.uecdn.es/rss/baloncesto/basketfeb.xml"
  "https://e00-marca.uecdn.es/rss/baloncesto/acb.xml"
  "https://e00-marca.uecdn.es/rss/motor/formula1.xml"
  # Mundo Deportivo extra (4) — confirmadas FeedSpot
  "https://www.mundodeportivo.com/feed/rss/futbol/ligue-1"
  "https://www.mundodeportivo.com/feed/rss/elotromundo"
  "https://www.mundodeportivo.com/feed/rss/ufc"
  "https://www.mundodeportivo.com/feed/rss/beisbol"
  # Sport España (2) — 1 confirmada FeedSpot
  "https://www.sport.es/es/rss/last-news/news.xml"
  "https://e00-marca.uecdn.es/rss/en/index.xml"
  # Cinco Días (5)
  "https://feeds.elpais.com/mrss-s/pages/ep/site/cincodias.elpais.com/portada"
  "https://feeds.elpais.com/mrss-s/list/ep/site/elpais.com/section/opinion"
  "https://feeds.elpais.com/mrss-s/list/ep/site/elpais.com/section/babelia"
  "https://feeds.elpais.com/mrss-s/list/ep/site/elpais.com/section/eps"
  "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/tecnologia/portada"
)

OK=0
FAIL=0

echo "Comprobando ${#URLS[@]} URLs RSS..."
echo "---"

for url in "${URLS[@]}"; do
  status=$(curl -s -o /dev/null -w "%{http_code}" --max-time 8 -L "$url")
  if [[ "$status" == "200" ]]; then
    echo "OK  [$status] $url"
    ((OK++))
  else
    echo "NOK [$status] $url"
    ((FAIL++))
  fi
done

echo ""
echo "=== RESULTADO ==="
echo "OK:   $OK / ${#URLS[@]}"
echo "FAIL: $FAIL / ${#URLS[@]}"
