[pytest]
# Evitar recoger/recursar en el directorio de pruebas de carga externo
norecursedirs = devops_verifica-main
collect_ignore = devops_verifica-main

# Solo tratar como tests los archivos con patrón test_*.py
python_files = test_*.py
